version: '3'

services:
    #mysql
    db:
      image: mysql:8.0
      container_name: mysql_host
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: app
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
        TZ: 'Asia/Tokyo'
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-endpoint-initdb.d
      ports:
      - 3306:3306
